"""
LLM Generator Module

Provides a provider-agnostic interface for generating answers using:
  - Google Gemini (default, set LLM_PROVIDER=gemini)
  - OpenAI         (fallback, set LLM_PROVIDER=openai)

The provider and API keys are loaded from environment variables.
API keys are NEVER exposed to the frontend.

Usage:
    generator = LLMGenerator()
    answer = await generator.generate_answer("What is CRISPR?")
    explanation = await generator.llm_judge(question, answer, evidence, score)
"""

import os
import asyncio
from pathlib import Path

from dotenv import load_dotenv

# Load .env from project root (backend/../.env)
_project_root = Path(__file__).resolve().parent.parent.parent
_env_file = _project_root / ".env"
load_dotenv(dotenv_path=_env_file if _env_file.exists() else None, override=False)
load_dotenv(override=False)


class LLMGenerator:
    """
    Wraps Gemini and OpenAI clients with a unified async interface.
    The provider is selected via the LLM_PROVIDER environment variable.
    """

    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "openai").lower().strip()
        self._client = None
        self._init_client()

    # ─── Client Initialization ────────────────────────────────────────────────

    def _init_client(self):
        """Initialize the LLM client based on the configured provider."""
        if self.provider == "gemini":
            self._init_gemini()
        elif self.provider == "openai":
            self._init_openai()
        else:
            raise ValueError(
                f"Unknown LLM_PROVIDER: '{self.provider}'. "
                "Set LLM_PROVIDER to 'gemini' or 'openai' in your .env file."
            )

    def _init_gemini(self):
        """Initialize Google Gemini client."""
        try:
            import google.generativeai as genai
        except ImportError:
            raise ImportError(
                "google-generativeai is not installed. "
                "Run: pip install google-generativeai"
            )

        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "GEMINI_API_KEY is not set. "
                "Add it to your .env file. "
                "Get a key at: https://aistudio.google.com/app/apikey"
            )

        genai.configure(api_key=api_key)
        model_name = os.getenv("GEMINI_MODEL", "gemini-3.5-flash")
        self._client = genai.GenerativeModel(model_name=model_name)
        self._model_name = model_name

    def _init_openai(self):
        """Initialize OpenAI client."""
        try:
            from openai import AsyncOpenAI
        except ImportError:
            raise ImportError(
                "openai is not installed. "
                "Run: pip install openai"
            )

        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "OPENAI_API_KEY is not set. "
                "Add it to your .env file."
            )

        self._client = AsyncOpenAI(api_key=api_key)
        self._model_name = os.getenv("OPENAI_MODEL", "gpt-3.5-turbo")

    # ─── Public Interface ─────────────────────────────────────────────────────

    async def generate_answer(self, question: str) -> str:
        """
        Generate an answer for any user question.

        Args:
            question: The user's free-form question.

        Returns:
            A string answer generated by the LLM.

        Raises:
            RuntimeError: If the LLM call fails.
        """
        prompt = self._build_answer_prompt(question)

        if self.provider == "gemini":
            return await self._generate_gemini(prompt)
        else:
            return await self._generate_openai(prompt)

    async def llm_judge(
        self,
        question: str,
        answer: str,
        top_evidence: str,
        similarity_score: float,
    ) -> dict:
        """
        Use the LLM as a judge to evaluate whether the answer is supported
        by the evidence and produce a natural-language risk explanation.

        Args:
            question:         The original user question.
            answer:           The LLM-generated answer.
            top_evidence:     The most relevant evidence passage retrieved.
            similarity_score: Cosine similarity between answer and evidence (0–1).

        Returns:
            dict with keys:
              - riskExplanation: str  (1–2 sentence explanation)
              - recommendation:  str  (specific advice for the user)
        """
        prompt = self._build_judge_prompt(question, answer, top_evidence, similarity_score)

        if self.provider == "gemini":
            raw = await self._generate_gemini(prompt)
        else:
            raw = await self._generate_openai(prompt)

        return self._parse_judge_response(raw)

    # ─── Prompt Templates ─────────────────────────────────────────────────────

    @staticmethod
    def _build_answer_prompt(question: str) -> str:
        return (
            "You are a knowledgeable and factual assistant. "
            "Answer the following question clearly and concisely based on your knowledge. "
            "Be accurate and avoid speculation. "
            "If you are unsure, say so honestly rather than guessing.\n\n"
            f"Question: {question}\n\n"
            "Answer:"
        )

    @staticmethod
    def _build_judge_prompt(
        question: str, answer: str, evidence: str, score: float
    ) -> str:
        return (
            "You are an AI fact-checking expert. "
            "Your task is to evaluate whether an AI-generated answer is supported by the provided evidence.\n\n"
            f"ORIGINAL QUESTION:\n{question}\n\n"
            f"AI-GENERATED ANSWER:\n{answer}\n\n"
            f"RETRIEVED EVIDENCE:\n{evidence}\n\n"
            f"SEMANTIC SIMILARITY SCORE: {score:.2f} (0=no match, 1=perfect match)\n\n"
            "Based on the evidence and similarity score, provide:\n"
            "1. RISK_EXPLANATION: A 1-2 sentence explanation of why this answer may or may not be reliable, "
            "referencing the evidence specifically.\n"
            "2. RECOMMENDATION: A specific, actionable recommendation for the user "
            "(e.g., 'Cross-check with official sources', 'The answer appears well-supported; "
            "minor verification recommended').\n\n"
            "Format your response EXACTLY as:\n"
            "RISK_EXPLANATION: [your explanation]\n"
            "RECOMMENDATION: [your recommendation]"
        )

    @staticmethod
    def _parse_judge_response(raw: str) -> dict:
        """Parse the LLM judge's structured response into a dict."""
        lines = raw.strip().splitlines()
        result = {
            "riskExplanation": "Unable to generate risk explanation.",
            "recommendation": "Verify this information with authoritative sources.",
        }

        for line in lines:
            if line.startswith("RISK_EXPLANATION:"):
                result["riskExplanation"] = line.replace("RISK_EXPLANATION:", "").strip()
            elif line.startswith("RECOMMENDATION:"):
                result["recommendation"] = line.replace("RECOMMENDATION:", "").strip()

        # Fallback: if parsing failed but we have content, use the full text
        if result["riskExplanation"] == "Unable to generate risk explanation." and raw.strip():
            parts = raw.strip().split("\n", 2)
            if len(parts) >= 1:
                result["riskExplanation"] = parts[0][:300]
            if len(parts) >= 2:
                result["recommendation"] = parts[1][:300]

        return result

    # ─── Provider-Specific Calls ──────────────────────────────────────────────

    async def _generate_gemini(self, prompt: str) -> str:
        """Call Google Gemini API asynchronously."""
        try:
            # google-generativeai's generate_content is synchronous;
            # run it in a thread pool to avoid blocking the event loop.
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self._client.generate_content(prompt),
            )
            if not response or not response.text:
                raise RuntimeError("Gemini returned an empty response.")
            return response.text.strip()
        except Exception as exc:
            raise RuntimeError(f"Gemini API error: {exc}") from exc

    async def _generate_openai(self, prompt: str) -> str:
        """Call OpenAI API asynchronously."""
        try:
            response = await self._client.chat.completions.create(
                model=self._model_name,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=800,
                temperature=0.3,
            )
            content = response.choices[0].message.content
            if not content:
                raise RuntimeError("OpenAI returned an empty response.")
            return content.strip()
        except Exception as exc:
            raise RuntimeError(f"OpenAI API error: {exc}") from exc
